import "~/styles/globals.css";

import { GeistSans } from 'geist/font/sans'
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/navbar";
import LoginButton from "./_components/login-button";
import Script from "next/script";

export const metadata = {
    title: "Litics",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const getCookieString = () => Promise.resolve(cookies().toString());

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Script defer src="https://litics.ecwrd.com/script.js" />
            <body
                className={`font-sans ${GeistSans.variable} flex min-h-screen flex-col bg-neutral-800 text-white`}
            >
                <TRPCReactProvider cookiePromise={getCookieString()}>
                    <Navbar loginButton={await LoginButton()} />
                    {children}
                </TRPCReactProvider>
            </body>
        </html>
    );
}

export const runtime = "edge";
